narratio_web_oeuvres_homepage:
    path:     /accueil
    defaults: { _controller: NarratioWebOeuvresBundle:Default:index }
    
        
narratio_web_oeuvres_rechercheAvancee:
    path:     /rechercheAvancee
    defaults: { _controller: NarratioWebOeuvresBundle:Default:rechercheAvancee }
    
narratio_web_oeuvres_oeuvre:
    path:     /oeuvre/{id}
    defaults: { _controller: NarratioWebOeuvresBundle:Default:oeuvre}
    requirements : 
        id: \d+
