narratio_web_oeuvres_homepage:
    path:     /accueil
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:index }
    
narratio_web_oeuvres_rechercheAvancee:
    path:     /rechercheAvancee
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:rechercheAvancee }
    
narratio_web_oeuvres_oeuvreAvanceeFilms:
    path:     /oeuvreAvanceeFilms/{page}/{tabFilmsIdBrut}/{filmsId}
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:oeuvreAvanceeFilms }
    
narratio_web_oeuvres_oeuvreAvanceeLivres:
    path:     /oeuvreAvanceeLivres/{page}/{tabLivresIdBrut}/{livresId}
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:oeuvreAvanceeLivres }
    
narratio_web_oeuvres_voirOeuvre:
    path:     /oeuvre/{id}
    defaults:    { _controller: NarratioWebOeuvresBundle:Oeuvre:voirOeuvre }
    requirements:
        id: \d+
       
narratio_web_oeuvres_vote:
    path:     /oeuvre/{id}/{nEtoile}
    defaults:    { _controller: NarratioWebOeuvresBundle:Oeuvre:vote }
    requirements:
        id: \d+

narratio_web_oeuvres_oeuvreMenu:
    path:     /oeuvre/{id}
    defaults:    { _controller: NarratioWebOeuvresBundle:Oeuvre:oeuvre }

#Pages réservées aux membres
narratio_web_oeuvres_ajouterOeuvre:
    path:     /membre/ajoutOeuvre
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:ajouterOeuvre }

narratio_web_oeuvres_modifierOeuvre:
    path:     /membre/modifierOeuvre/{type}/{id}
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:modifierOeuvre }