narratio_web_oeuvres_homepage:
    path:     /accueil
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:index }
    
narratio_web_oeuvres_rechercheAvancee:
    path:     /rechercheAvancee
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:rechercheAvancee }
    
narratio_web_oeuvres_oeuvreAvanceeFilms:
    path:     /oeuvreAvanceeFilms/{page}
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:oeuvreAvancee }
    
narratio_web_oeuvres_oeuvreAvanceeLivres:
    path:     /oeuvreAvanceeLivres/{page}
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:oeuvreAvancee }
    
narratio_web_oeuvres_voirOeuvre:
    path:     /oeuvre/{id}
    defaults:    { _controller: NarratioWebOeuvresBundle:Oeuvre:voirOeuvre }
    requirements:
        id: \d+

narratio_web_oeuvres_oeuvreMenu:
    path:     /oeuvre/{id}
    defaults:    { _controller: NarratioWebOeuvresBundle:Oeuvre:oeuvre }
    
naratio_web_oeuvres_test:
    path: /haize
    defaults:   { _controller: NarratioWebOeuvresBundle:Oeuvre:test }
    
narratio_web_oeuvres_connexion:
    path:     /accueil/connexion
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:connexion }

narratio_web_oeuvres_inscription:
    path:     /accueil/inscription
    defaults: { _controller: NarratioWebOeuvresBundle:Oeuvre:inscription }
    
