narratio_web_oeuvres_homepage:
    path:     /accueil
    defaults: { _controller: NarratioWebOeuvresBundle:Default:index }
    
        
narratio_web_oeuvres_rechercheAvancee:
    path:     /rechercheAvancee
    defaults: { _controller: NarratioWebOeuvresBundle:Default:rechercheAvancee }
    
narratio_web_oeuvres_oeuvre:
    path:     /oeuvre/{choixGenre}/{choixEpoque}/{choixTrancheAge}
    defaults:    { _controller: NarratioWebOeuvresBundle:Default:oeuvre }
    
narratio_web_oeuvres_voirOeuvre:
    path:     /oeuvre/{id}
    defaults:    { _controller: NarratioWebOeuvresBundle:Default:voirOeuvre }
    
narratio_web_oeuvres_oeuvreAvanceeFilm:
    path:     /oeuvreCine/{choixGenreF}/{choixEpoqueF}/{choixTrancheAgeF}/{choixActeur}/{choixRealisateur}/{choixThematiqueF}/{choixType}
    defaults:    { _controller: NarratioWebOeuvresBundle:Default:oeuvreAvanceeFilm }
    
narratio_web_oeuvres_oeuvreMenu:
    path:     /oeuvre/{id}
    defaults:    { _controller: NarratioWebOeuvresBundle:Default:oeuvre }
    
naratio_web_oeuvres_test:
    path: /haize
    defaults:   { _controller: NarratioWebOeuvresBundle:Default:test }