narratio_web_oeuvres_homepage:
    path:     /accueil
    defaults: { _controller: NarratioWebOeuvresBundle:Default:index }
    
        
narratio_web_oeuvres_rechercheAvancee:
    path:     /rechercheAvancee
    defaults: { _controller: NarratioWebOeuvresBundle:Default:rechercheAvancee }
    
narratio_web_oeuvres_oeuvre:
    path:     /oeuvre/{choixGenre}/{choixEpoque}/{choixTrancheAge}
    defaults:    { _controller: NarratioWebOeuvresBundle:Default:oeuvre}
    
narratio_web_oeuvres_essai:
    path:   /test
    defaults:    { _controller: NarratioWebOeuvresBundle:Default:essai}