<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EpoqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpoqueRepository extends EntityRepository
{
    
    public function intituleEpoque()
    {
    
        $gestionnaire = $this->_em;
        
        // Création requête
        $requete = $gestionnaire->createQuery('SELECT e.intitule FROM NarratioWebOeuvresBundle:Epoque e');
        
        // Exécution requête
        $tabEpoque = $requete->getResult();
        
        return $tabEpoque;
        

    }
}
