<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EpoqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EpoqueRepository extends EntityRepository
{
    
    public function Intitule($limit)
    {
    return $this->_em->createQuery('
        SELECT
            intitule
        FROM
            NarratioWebOeuvresBundle:Epoque;
    ')
    ->setMaxResults($limit)
    ->setParameter('enabled', true);
    }
}
