<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
    
    public function intituleGenre()
    {
    
        $gestionnaire = $this->_em;
        
        // Création requête
        $requete = $gestionnaire->createQuery('SELECT g.intitule FROM NarratioWebOeuvresBundle:Genre g');
        
        // Exécution requête
        $tabGenre = $requete->getResult();
        
        return $tabGenre;
        

    }
    
}
