<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends EntityRepository
{

    public function getLivresByOeuvre($idOeuvre) // OK
    {
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT l FROM NarratioWebOeuvresBundle:Livre l
                                                                    WHERE l.oeuvre = :idOeuvre
                                                        ');
                                         
        // je definis mes parametres
        $requetePerso->setParameter('idOeuvre', $idOeuvre);
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
    }
    
    
    public function getLivresAvancee($choixAuteur, $choixEditeur)
    {
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT l FROM NarratioWebOeuvresBundle:Livre l
                                                            LEFT JOIN l.auteur a
                                                                    WHERE (l.editeur = :choixEditeur
                                                                        AND a.id = :choixAuteur)
                                                                        OR
                                                                        (l.editeur = :choixEditeur
                                                                        AND (NOT a.id = :choixAuteur))
                                                                        OR
                                                                        ((NOT l.editeur = :choixEditeur)
                                                                        AND a.id = :choixAuteur)
                                                        ');
                                         
        // je definis mes parametres
        $requetePerso->setParameter('choixAuteur', $choixAuteur);
        $requetePerso->setParameter('choixEditeur', $choixEditeur);
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
    }
    
}