<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OeuvreCineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeuvreCineRepository extends EntityRepository
{
    
        public function getOeuvreCine($choixEpoque, $choixGenre, $choixTrancheAge, $choixActeur, $choixRealisateur, $choixType, $choixThematique)
    {
        
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT o FROM NarratioWebOeuvresBundle:Oeuvre o 
                                                                        WHERE o.genre = :choixGenre
                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.trancheAge = :choixTrancheAge
                                                                        ');
        
        // je definis mes parametres
        $requetePerso->setParameter('choixEpoque', $choixEpoque);
        $requetePerso->setParameter('choixGenre', $choixGenre);
        $requetePerso->setParameter('choixTrancheAge', $choixTrancheAge);
        $requetePerso->setParameter('choixActeur', $choixActeur);
        $requetePerso->setParameter('choixRealisateur', $choixRealisateur);
        $requetePerso->setParameter('choixType', $choixType);
        $requetePerso->setParameter('choixThematique', $choixThematique);
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
        
    }
    
}

/*

        $requetePerso = $gestionnaireEntite->createQuery('SELECT o FROM NarratioWebOeuvresBundle:Oeuvre o 
                                                                        WHERE o.genre = :choixGenre
                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.trancheAge = :choixTrancheAge
                                                                                                                                                AND o.epoque = :choixEpoque
                                                                        AND o.acteur = :choixActeur                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.realisateur = :choixRealisateur                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.type = :choixType                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.thematique = :choixThematique
                                                                        
                                                                        ');
                                                                        
*/