<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OeuvreLittRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeuvreLittRepository extends EntityRepository
{
    
    public function getOeuvreLitt($choixEpoque, $choixGenre, $choixTrancheAge)
    {
        
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT o FROM NarratioWebOeuvresBundle:Oeuvre o 
                                                                        WHERE o.genre = :choixGenre
                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.trancheAge = :choixTrancheAge
                                                                        ');
        
        // je definis mes parametres
        $requetePerso->setParameter('choixEpoque', $choixEpoque);
        $requetePerso->setParameter('choixGenre', $choixGenre);
        $requetePerso->setParameter('choixTrancheAge', $choixTrancheAge);
        //$requetePerso->setParameter('choixActeur', $choixActeur);
        //$requetePerso->setParameter('choixRealisateur', $choixRealisateur);
        //$requetePerso->setParameter('choixType', $choixType);
        //$requetePerso->setParameter('choixThematique', $choixThematique);
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
        
    }
    
    public function getLivres()
    {
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT l FROM NarratioWebOeuvresBundle:Livre l WHERE l.oeuvreLitt = :id');
        
        // je definis mes parametres
        $requetePerso->setParameter('id', $id);
        
        //je fixe ma limite à 3 résultats
        $requetePerso->setMaxResults(3);
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
    }
        
}

/*

        $requetePerso = $gestionnaireEntite->createQuery('SELECT o FROM NarratioWebOeuvresBundle:Oeuvre o 
                                                                        WHERE o.genre = :choixGenre
                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.trancheAge = :choixTrancheAge
                                                                                                   
                                                                                                   
                                                                        AND o.discr = "oeuvrelitt"
                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.acteur = :choixActeur                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.realisateur = :choixRealisateur                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.type = :choixType                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.thematique = :choixThematique
                                                                        
                                                                        ');
                                                                        
*/