<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OeuvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OeuvreRepository extends EntityRepository
{
    
    public function getOeuvreChoix($choixEpoque, $choixGenre, $choixTrancheAge)
    {
        
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT o.nom, o.id, o FROM NarratioWebOeuvresBundle:Oeuvre o
                                                                        WHERE o.genre = :choixGenre
                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.trancheAge = :choixTrancheAge
                                                                        ORDER BY o.nom, o.id
                                                                        
                                                        ');
                                            
                                            
        // je definis mes parametres
        $requetePerso->setParameter('choixEpoque', $choixEpoque);
        $requetePerso->setParameter('choixGenre', $choixGenre);
        $requetePerso->setParameter('choixTrancheAge', $choixTrancheAge);
                        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
        
    }
    
    public function getOeuvreRecentes()
    {
         // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT DISTINCT o.id, o FROM NarratioWebOeuvresBundle:Oeuvre o ORDER BY o.id DESC');
        
        /*//je fixe ma limite à 3 résultats
        $requetePerso->setMaxResults(4);*/
                                            
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
    }
    
    public function getOeuvrePlusVues()
    {
         // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT DISTINCT o.id, o FROM NarratioWebOeuvresBundle:Oeuvre o ORDER BY o.compteurVues DESC');
                                            
        /*//je fixe ma limite à 3 résultats
        $requetePerso->setMaxResults(4);*/
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
    }
    
    public function getLivres($id)
    {
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT l FROM NarratioWebOeuvresBundle:Livre l JOIN l.oeuvreLitt o WHERE o.id = :idOeuvre');
        
        //Je définis les paramètres de ma requête
        $requetePerso->setParameter('idOeuvre', $id);
        
        //je fixe ma limite à 3 résultats
        $requetePerso->setMaxResults(3);
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
    }
    
    public function getFilms($id)
    {
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT f FROM NarratioWebOeuvresBundle:Film f JOIN l.oeuvreCine o WHERE o.id = :idOeuvre');
        
        //Je définis la valeur de mon paramètre
        $requetePerso->setParameter('idOeuvre', $id);
        
        //je fixe ma limite à 3 résultats
        $requetePerso->setMaxResults(3);
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
    }
}




/*



SELECT DISTINCT o.nom, o FROM NarratioWebOeuvresBundle:Oeuvre o
                                                                        WHERE o.genre = :choixGenre
                                                                        AND o.epoque = :choixEpoque
                                                                        AND o.trancheAge = :choixTrancheAge



*/