<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitDerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitDerRepository extends EntityRepository
{
    
    
        
    public function getProdsByOeuvreProd($idProd)
    {
        // appel du gestionnaire d'entité
        $gestionnaireEntite = $this->_em;
        
        // ecriture de la requete personnalisée
        $requetePerso = $gestionnaireEntite->createQuery('SELECT p FROM NarratioWebOeuvresBundle:ProduitDer p
                                                                    WHERE p.id = :idProd
                                                        ');
                                         
        // je definis mes parametres
        $requetePerso->setParameter('idProd', $idProd);
        
        // execution de la requete et recup du resultat
        $tabResultats = $requetePerso -> getResult();
        
        // retour du resultat
        return $tabResultats;
    }
    
    
}
