<?php

namespace NarratioWeb\OeuvresBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrancheAgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrancheAgeRepository extends EntityRepository
{
    
        public function intituleTrancheAge()
    {
    
        $gestionnaire = $this->_em;
        
        // Création requête
        $requete = $gestionnaire->createQuery('SELECT DISTINCT t.intitule FROM NarratioWebOeuvresBundle:TrancheAge t');
        
        // Exécution requête
        $tabTrancheAge = $requete->getResult();
        
        return $tabTrancheAge;
        

    }
    
}
