form_login:
    csrf_provider:       form.csrf_provider
    login_path:          fos_user_security_login
    check_path:          fos_user_security_check
    default_target_path: NarratioWeb_Oeuvre_index
    logout:       true
    anonymous:    true
    logout:
        path:   /NarratioWeb_Oeuvre/User/logout
        target: /NarratioWeb_Oeuvre/accueil